zuul:
  routes:
    userprovider:
      path: /service/**
      url: USERPROVIDER
  retryable: true

spring:
  application:
    name: zuul
server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka,http://localhost:8889/eureka

ribbon:
  #配置指定服务的负载均衡策略
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
  # Ribbon 的连接超时时间
  ConnectTimeout: 250
  # Ribbon 的数据读取超时时间
  ReadTimeout: 250
  # 是否对所有操作都进行重试
  OkToRetryOnAllOperations: true
  # 切换实例的重试次数
  MaxAutoRetriesNextServer: 1
  # 对当前实例的重试次数
  MaxAutoRetries: 5

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 9000
