spring:
  application:
    name: UserWeb03
  thymeleaf:
    cache: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8887/eureka,http://localhost:8889/eureka
server:
  port: 9006
logging:
  level:
    com:
      ujiuy: debug
