server:
  port: 8889
spring:
  application:
    name: EurekaServers
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 1000
