spring:
  application:
    name: config_server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mean-to/config_
          search-paths:
          username: 2572482562@qq.com
          password: ma19980105
server:
  port: 8891
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka,http://localhost:8889/eureka